version: '3.8'

networks:
  app-network:
    driver: bridge

services:
  # Frontend Service
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

  # Backend Service
  backend:
    build:
      context: .
      dockerfile: docker-container/finlab python/apps/dashboard-backend/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/forum_autoposter
      - PYTHONPATH=/
    networks:
      - app-network
    depends_on:
      - db
    restart: unless-stopped

  # Database
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: forum_autoposter
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: unless-stopped

volumes:
  postgres_data:
