[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = [
  "cd docker-container/finlab python/apps/unified-api && pip install -r requirements.txt"
]

[phases.build]
cmds = [
  "echo 'Building Unified API...'"
]

[start]
cmd = "cd docker-container/finlab python/apps/unified-api && uvicorn main:app --host 0.0.0.0 --port $PORT"
