[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = [
  "cd docker-container/finlab python/apps/api-gateway && pip install -r requirements.txt"
]

[phases.build]
cmds = [
  "echo 'Building API Gateway...'",
  "chmod +x start.sh"
]

[start]
cmd = "sh start.sh"
