[phases.setup]
nixPkgs = ["python311", "nodejs_18"]

[phases.install]
cmds = [
  "pip install -r requirements.txt",
  "cd docker-container/finlab python/apps/api-gateway && pip install -r requirements.txt"
]

[phases.build]
cmds = [
  "echo 'Building API Gateway...'"
]

[start]
cmd = "cd docker-container/finlab python/apps/api-gateway && uvicorn main:app --host 0.0.0.0 --port $PORT"
