[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = [
  "cd docker-container/finlab python/apps/unified-api && pip install -r requirements.txt"
]

[phases.build]
cmds = [
  "echo 'Building Unified API...'",
  "chmod +x start-unified-api.sh"
]

[start]
cmd = "sh start-unified-api.sh"
