version: '3.8'

services:
  posting-service:
    build: ./docker-container/finlab python/apps/posting-service
    ports:
      - "8001:8000"
    env_file:
      - .env
    environment:
      - TRENDING_API_URL=http://trending-api:8004
      - OHLC_API_URL=http://ohlc-api:8005
      - ANALYZE_API_URL=http://analyze-api:8002
    volumes:
      - ./src:/app/src
      - ./post_records:/app/post_records
      - ./docker-container/finlab python/apps/posting-service:/app
    depends_on:
      - trending-api
      - ohlc-api
      - analyze-api

  ohlc-api:
    build: ./docker-container/finlab python/apps/ohlc-api
    ports:
      - "8005:8000"
    env_file:
      - .env

  analyze-api:
    build: ./docker-container/finlab python/apps/analyze-api
    ports:
      - "8002:8000"

  summary-api:
    build: ./docker-container/finlab python/apps/summary-api
    ports:
      - "8003:8000"
    environment:
      - OHLC_API_URL=http://ohlc-api:8005
      - ANALYZE_API_URL=http://analyze-api:8002
    depends_on:
      - ohlc-api
      - analyze-api

  trending-api:
    build: ./docker-container/finlab python/apps/trending-api
    ports:
      - "8004:8004"

  dashboard-api:
    build: ./docker-container/finlab python/apps/dashboard-api
    ports:
      - "8007:8007"

  financial-api:
    build: ./docker-container/finlab python/apps/financial-api
    ports:
      - "8006:8000"

networks:
  default:
    name: finlab-network