services:
  ohlc-api:
    build:
      context: ..
      dockerfile: apps/ohlc-api/Dockerfile
    env_file: ../.env
    ports: ["8001:8000"]

  analyze-api:
    build:
      context: ..
      dockerfile: apps/analyze-api/Dockerfile
    env_file: ../.env
    ports: ["8002:8000"]
    depends_on: ["ohlc-api"]

  summary-api:
    build:
      context: ..
      dockerfile: apps/summary-api/Dockerfile
    env_file: ../.env
    ports: ["8003:8000"]
    depends_on: ["ohlc-api", "analyze-api"]

  trainer:
    build:
      context: ..
      dockerfile: apps/trainer/Dockerfile
    env_file: ../.env
    ports: ["8004:8000"]
    depends_on: ["ohlc-api", "analyze-api"]

  trending-api:
    build:
      context: ..
      dockerfile: apps/trending-api/Dockerfile
    env_file: ../.env
    ports: ["8005:8000"]

  posting-service:
    build:
      context: ..
      dockerfile: apps/posting-service/Dockerfile
    env_file: ../.env
    ports: ["8006:8000"]
    depends_on: ["trending-api", "summary-api", "ohlc-api"]