[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "shared"
version = "0.1.0"
description = "Shared schemas and utilities"
authors = [{name="Your Team"}]
requires-python = ">=3.10"
dependencies = [
    "pydantic>=2.7.0",
    "requests>=2.31.0",
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]